server.port=8080

# Production Secure Cluster Configuration
spring.datasource.url=jdbc:postgresql://prod-failover-aurora:5432/fraud_db_prod
spring.datasource.username=fraud_prod_application
spring.datasource.password=highly_secure_vault_managed_secret
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

# Enforce secure transport parameters for high-level compliance environments
spring.datasource.hikari.data-source-properties.ssl=true
spring.datasource.hikari.maximum-pool-size=20

# Production Cache & High-Availability Streams Brokers
spring.data.redis.host=prod-elasticache-redis-writer
spring.data.redis.port=6379

spring.kafka.bootstrap-servers=prod-kafka-01:9092,prod-kafka-02:9092,prod-kafka-03:9092
spring.kafka.consumer.group-id=fraud-detection-prod-group
spring.kafka.consumer.auto-offset-reset=latest
