server.port=8080

# Logging drops back to INFO to keep log noise clean during heavy QA testing
logging.level.com.bragdev.frauddetection=INFO

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
# Enterprise Safe Guard: Validate schemas, do NOT alter database tables automatically
spring.jpa.hibernate.ddl-auto=validate

spring.data.redis.host=${SPRING_REDIS_HOST}
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS}
